language: python
python:
  - '3.6.3'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -O /tmp/chromedriver
  - chmod 777 /tmp/chromedriver
install:
  - pip install pipenv && pipenv install --dev
before_script:
  - cd superlists
script:
  - pipenv run python manage.py test
notifications:
  email: false
