sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: python
python:
  - '3.6.3'
install:
  - pip install pipenv && pipenv install --dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
  - cd superlists
script:
  - pipenv run python manage.py test
notifications:
  email: false
