sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: python
python:
  - '3.6.3'
install:
  - pip install pipenv && pipenv install --dev
before_script:
  - cd superlists
env:
  - CHROME_DRIVER_PATH=/usr/local/bin/chromedriver
script:
  - pipenv run python manage.py test
notifications:
  email: false
