language: python
python:
  - '3.6.3'
env:
  - DJANGO=1.11.7
before_script:
  - pip install pipenv && pipenv shell && pipenv install && cd superlists
script:
  - pipenv run python manage.py test
  - pipenv run python functional_tests.py
  